// Emits cross-check vectors for the client's decoders.
//
// The client has its own implementation of both bitstreams, in TypeScript, and
// nothing structural stops the two drifting apart. This writes a JSON file of
// encoded frames alongside the samples the C++ decoder produces from them;
// web/src/dsp/vectors.test.ts decodes the same bytes and must agree.
//
//   make -C server vectors      -> web/src/dsp/testdata/vectors.json
#include <cmath>
#include <cstdio>
#include <random>
#include <string>
#include <vector>

#include "../src/codec/nac.h"
#include "../src/codec/waterfall_codec.h"
#include "../src/codec/waterfall_rc.h"
#include "../src/core/protocol.h"

namespace {

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string out;
    out.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        out += digits[b >> 4];
        out += digits[b & 15];
    }
    return out;
}

std::string format_float(float value) {
    char buffer[32];
    snprintf(buffer, sizeof(buffer), "%.7g", static_cast<double>(value));
    return buffer;
}

// A signal with something for every part of the codec to chew on: two tones
// far apart in level, plus noise.
std::vector<float> make_signal(size_t samples, double rate, uint32_t seed) {
    std::mt19937 rng(seed);
    std::normal_distribution<float> noise(0.0f, 0.02f);
    std::vector<float> out(samples);
    for (size_t i = 0; i < samples; i++) {
        const double t = static_cast<double>(i) / rate;
        out[i] = static_cast<float>(0.45 * std::sin(2.0 * M_PI * 900.0 * t) +
                                    0.01 * std::sin(2.0 * M_PI * 2400.0 * t)) +
                 noise(rng);
    }
    return out;
}

}  // namespace

int main(int argc, char** argv) {
    const std::string path = argc > 1 ? argv[1] : "web/src/dsp/testdata/vectors.json";
    FILE* file = fopen(path.c_str(), "w");
    if (!file) {
        fprintf(stderr, "cannot write %s\n", path.c_str());
        return 1;
    }

    fprintf(file, "{\n  \"note\": \"Generated by server/tools/gen_vectors.cpp; run 'make -C server vectors'.\",\n");

    // --- audio ---
    fprintf(file, "  \"audio\": [\n");
    const int rates[] = {8000, 12000};
    const int bitrates[] = {24000, 48000, 96000};
    bool first_case = true;
    for (int rate : rates) {
        for (int bitrate : bitrates) {
            if (!first_case) fprintf(file, ",\n");
            first_case = false;

            fernsdr::nac::Encoder encoder(rate);
            encoder.set_bitrate(bitrate);
            fernsdr::nac::Encoder legacy(rate);
            legacy.set_bitrate(bitrate);
            fernsdr::nac::Decoder decoder(rate);

            auto signal = make_signal(fernsdr::nac::kFrameHop * 24, rate, static_cast<uint32_t>(rate + bitrate));

            fprintf(file, "    {\"sample_rate\": %d, \"bitrate\": %d, \"frames\": [\n", rate, bitrate);
            std::vector<float> decoded(fernsdr::nac::kFrameHop);
            for (size_t offset = 0; offset + fernsdr::nac::kFrameHop <= signal.size();
                 offset += fernsdr::nac::kFrameHop) {
                const auto& payload = encoder.encode(signal.data() + offset, offset / fernsdr::nac::kFrameHop % 5 != 0);
                const auto& original = legacy.encode(signal.data() + offset);
                decoder.decode(payload.data(), payload.size(), decoded.data(), encoder.used_compact());

                fprintf(file, "      {\"payload\": \"%s\", \"legacy_payload\": \"%s\", \"compact\": %s, \"samples\": [",
                        to_hex(payload).c_str(), to_hex(original).c_str(), encoder.used_compact() ? "true" : "false");
                for (size_t i = 0; i < decoded.size(); i++) {
                    fprintf(file, "%s%s", i ? "," : "", format_float(decoded[i]).c_str());
                }
                fprintf(file, "]}%s\n",
                        offset + 2 * fernsdr::nac::kFrameHop <= signal.size() ? "," : "");
            }
            fprintf(file, "    ]}");
        }
    }
    fprintf(file, "\n  ],\n");

    // Concealment: the client must decay identically, or a dropout sounds
    // different depending on which implementation is playing.
    {
        fernsdr::nac::Encoder encoder(12000);
        encoder.set_bitrate(48000);
        fernsdr::nac::Decoder decoder(12000);
        auto signal = make_signal(fernsdr::nac::kFrameHop * 6, 12000, 5);
        std::vector<float> decoded(fernsdr::nac::kFrameHop);
        std::vector<std::string> payloads;
        for (size_t offset = 0; offset + fernsdr::nac::kFrameHop <= signal.size();
             offset += fernsdr::nac::kFrameHop) {
            const auto& payload = encoder.encode(signal.data() + offset);
            payloads.push_back(to_hex(payload));
            decoder.decode(payload.data(), payload.size(), decoded.data());
        }

        fprintf(file, "  \"concealment\": {\"sample_rate\": 12000, \"payloads\": [");
        for (size_t i = 0; i < payloads.size(); i++) {
            fprintf(file, "%s\"%s\"", i ? "," : "", payloads[i].c_str());
        }
        fprintf(file, "], \"after\": [\n");
        for (int step = 0; step < 3; step++) {
            decoder.conceal(decoded.data());
            fprintf(file, "    [");
            for (size_t i = 0; i < decoded.size(); i++) {
                fprintf(file, "%s%s", i ? "," : "", format_float(decoded[i]).c_str());
            }
            fprintf(file, "]%s\n", step < 2 ? "," : "");
        }
        fprintf(file, "  ]},\n");
    }

    // NAC3 packets of one to four frames. The signal switches bands on and
    // off and falls silent, so masks change inside packets and later frames
    // predict from bands the first frame did not carry; the gain steps like
    // an AGC's so the noise estimate moves.
    fprintf(file, "  \"nac3\": [\n");
    {
        bool first_nac3 = true;
        for (int rate : {12000, 15625}) for (int bitrate : {16000, 48000}) {
            if (!first_nac3) fprintf(file, ",\n");
            first_nac3 = false;
            fernsdr::nac::Encoder encoder(rate);
            encoder.set_bitrate(bitrate);
            fernsdr::nac::Nac3Target target;
            if (rate == 12000) {
                target.passband_low_hz = 300;
                target.passband_high_hz = 2700;
            }
            encoder.set_target(target);
            fernsdr::nac::Decoder decoder(rate);
            std::mt19937 rng(static_cast<uint32_t>(rate * 7 + bitrate));
            std::normal_distribution<float> noise(0.0f, 0.01f);
            const size_t hops = 48;
            std::vector<float> signal(fernsdr::nac::kFrameHop * hops);
            for (size_t i = 0; i < signal.size(); i++) {
                const size_t hop = i / fernsdr::nac::kFrameHop;
                const double t = static_cast<double>(i) / rate;
                float value = noise(rng);
                if (hop % 12 < 7) value += static_cast<float>(0.3 * std::sin(2.0 * M_PI * 700.0 * t));
                if (hop % 9 > 3) value += static_cast<float>(0.05 * std::sin(2.0 * M_PI * 2100.0 * t));
                if (hop >= 30 && hop < 34) value = 0.0f;
                signal[i] = value;
            }
            fprintf(file, "    {\"sample_rate\": %d, \"bitrate\": %d, \"packets\": [\n", rate, bitrate);
            size_t hop = 0;
            int size = 1;
            bool first_packet = true;
            while (hop < hops) {
                const int frames = std::min<int>(size, static_cast<int>(hops - hop));
                encoder.begin_packet();
                for (int f = 0; f < frames; f++) {
                    encoder.set_signal_gain(hop % 16 < 8 ? 1.0f : 4.0f);
                    encoder.add_frame(signal.data() + (hop + f) * fernsdr::nac::kFrameHop);
                }
                const auto payload = encoder.finish_packet();
                std::vector<float> decoded(fernsdr::nac::kFrameHop * fernsdr::nac::kMaxPacketFrames);
                bool ok = false;
                decoder.decode_packet(payload.data(), payload.size(), decoded.data(), fernsdr::nac::kMaxPacketFrames, ok);
                if (!ok) {
                    fprintf(stderr, "NAC3 vector packet failed to decode\n");
                    return 1;
                }
                fprintf(file, "%s      {\"payload\": \"%s\", \"frames\": %d, \"samples\": [",
                        first_packet ? "" : ",\n", to_hex(payload).c_str(), frames);
                first_packet = false;
                for (size_t i = 0; i < static_cast<size_t>(frames) * fernsdr::nac::kFrameHop; i++) {
                    fprintf(file, "%s%s", i ? "," : "", format_float(decoded[i]).c_str());
                }
                fprintf(file, "]}");
                hop += static_cast<size_t>(frames);
                size = size % fernsdr::nac::kMaxPacketFrames + 1;
            }
            fprintf(file, "\n    ]}");
        }
    }
    fprintf(file, "\n  ],\n");

    // --- waterfall ---
    fprintf(file, "  \"waterfall\": [\n");
    const int widths[] = {64, 256, 1024, 512, 2, 15, 527};
    bool first_width = true;
    for (int precision : {1, 2}) for (int width : widths) {
        if (!first_width) fprintf(file, ",\n");
        first_width = false;

        fernsdr::wfc::LineEncoder encoder;
        std::mt19937 rng(static_cast<uint32_t>(width));
        std::normal_distribution<float> noise(0.0f, 2.0f);

        fprintf(file, "    {\"width\": %d, \"lines\": [\n", width);
        for (int l = 0; l < 12; l++) {
            std::vector<float> line(static_cast<size_t>(width));
            for (int i = 0; i < width; i++) {
                line[static_cast<size_t>(i)] =
                    -103.0f + noise(rng) + (i % 41 == 7 ? 38.0f : 0.0f) + 1.5f * std::sin(l * 0.3f);
            }
            // Force an intra line partway through, as a viewport change would.
            const bool force_intra = l == 6;
            if (width == 512) {
                for (int i = 0; i < width; i++) line[i] = -105.0f + (i % 41 == 7 ? 38.0f : 0.0f) + (l / 4);
            }
            if (width == 527) {
                for (int i = 0; i < width; i++) line[i] = -140.0f + i % 160 + (l % 4);
            }
            const int step_db = precision == 2 && l >= 3 && l < 9 ? 2 : 1;
            const auto& payload = encoder.encode(line.data(), line.size(), force_intra, true, width == 527 || width < 16, step_db);

            const auto mode = payload[0] >> (encoder.used_adaptive() ? 6 : 7);
            fprintf(file, "      {\"payload\": \"%s\", \"intra\": %s, \"zero_runs\": %s, \"adaptive\": %s, \"step_db\": %d, \"levels\": [",
                    to_hex(payload).c_str(), (mode == 1 || mode == 3) ? "true" : "false",
                    encoder.used_zero_runs() ? "true" : "false", encoder.used_adaptive() ? "true" : "false", step_db);
            for (int i = 0; i < width; i++) {
                // The decoder reproduces the quantised value, not the input.
                const int q = fernsdr::wfc::quantise_db(line[static_cast<size_t>(i)], step_db);
                fprintf(file, "%s%s", i ? "," : "",
                        format_float(static_cast<float>(q) * step_db).c_str());
            }
            fprintf(file, "]}%s\n", l < 11 ? "," : "");
        }
        fprintf(file, "    ]}");
    }
    fprintf(file, "\n  ],\n");

    // --- WFC5 range-coded rows ---
    // Quiet, averaged rows with carriers and a ramp; a forced key row, a
    // step change, a row at both ends of the level range, and more than one
    // key span.
    fprintf(file, "  \"waterfall_ranged\": [\n");
    const int ranged_widths[] = {1536, 64, 7};
    bool first_ranged = true;
    for (int width : ranged_widths) {
        if (!first_ranged) fprintf(file, ",\n");
        first_ranged = false;
        fernsdr::wfc::RangedLineEncoder encoder;
        std::mt19937 rng(static_cast<uint32_t>(width + 500));
        std::normal_distribution<float> noise(0.0f, 0.6f);
        fprintf(file, "    {\"width\": %d, \"lines\": [\n", width);
        const int lines = 60;
        for (int l = 0; l < lines; l++) {
            std::vector<float> line(static_cast<size_t>(width));
            for (int i = 0; i < width; i++) {
                line[static_cast<size_t>(i)] = -112.0f + noise(rng) + 2.0f * std::sin(l * 0.2f) +
                    (i % 97 == 13 ? 40.0f + l % 7 : 0.0f) + (i % 300 < 20 ? 0.8f * static_cast<float>(i % 300) : 0.0f);
            }
            if (l == 45) for (int i = 0; i < width; i++) line[static_cast<size_t>(i)] = (i % 3) ? 150.0f : -250.0f;
            const int step_db = l >= 30 ? 2 : 1;
            const auto& payload = encoder.encode(line.data(), line.size(), l == 10, step_db);
            fprintf(file, "      {\"payload\": \"%s\", \"key\": %s, \"step_db\": %d, \"levels\": [",
                    to_hex(payload).c_str(), encoder.last_was_key() ? "true" : "false", step_db);
            for (int i = 0; i < width; i++) {
                const int q = fernsdr::wfc::quantise_db(line[static_cast<size_t>(i)], step_db);
                fprintf(file, "%s%s", i ? "," : "", format_float(static_cast<float>(q) * step_db).c_str());
            }
            fprintf(file, "]}%s\n", l < lines - 1 ? "," : "");
        }
        fprintf(file, "    ]}");
    }
    fernsdr::proto::Meter meter;
    meter.dbfs = -103.2f;
    meter.gain_db = 42.7f;
    meter.squelch_statistic = 34.5f;
    meter.pll_offset = -123.4f;
    meter.audio_bps = 32000;
    meter.waterfall_bps = 8000;
    meter.waterfall_fps = 12.5f;
    meter.listeners = 1000;
    meter.squelch_open = meter.pll_locked = meter.auto_squelch = meter.sam = true;
    std::vector<uint8_t> packet(fernsdr::proto::kMeterBytes);
    fernsdr::proto::write_meter(packet.data(), meter);
    fprintf(file, "\n  ],\n  \"meter\": \"%s\"\n}\n", to_hex(packet).c_str());

    fclose(file);
    printf("wrote %s\n", path.c_str());
    return 0;
}
